name: Build Android APK (debug, no signing)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter (misma versión que usas localmente)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.7"
          channel: "stable"
          cache: true

      - name: Pub get
        run: flutter pub get

      # Compila APK de debug (sin firma de release)
      - name: Build APK (debug)
        run: flutter build apk --debug

      # Sube el APK como artifact
      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
